version: "3.1"
services:

    payaba-db:
      image: postgres:13-alpine
      container_name: sc-panel-db
      volumes:
        - "./postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1933
        - POSTGRES_DB=sc-panel
      ports:
      - "5432:5432"
      networks:
        - sc-panel
        - sc-host

networks:
  sc-panel:
  sc-host: